---
- name: add fedora36 repo
  yum_repository:
    name: fedora36-nagios
    baseurl: https://archives.fedoraproject.org/pub/archive/fedora/linux/updates/36/Everything/x86_64/
    description: "Fedora36 repo to be used for nagios plugins until amazon gets it together"
    enabled: false
    gpgkey: https://src.fedoraproject.org/rpms/fedora-repos/raw/rawhide/f/RPM-GPG-KEY-fedora-36-primary
    state: present
  when: ncpa_use_fedora_repo

- name: install nagios gpg key
  rpm_key:
   state: present
   key: https://repo.nagios.com/GPG-KEY-NAGIOS-V2

- name: install ncpa repo
  yum:
    name: "{{ ncpa_repo_package_url }}"
    state: present

- name: install ncpa package from url if specified
  yum:
    name: "{{ ncpa_package_url }}"
    state: present
  when: ncpa_package_url != ""

- name: install ncpa packages
  yum:
    name: "{{ ncpa_packages }}"
    state: present
  when: not ncpa_use_fedora_repo

- name: install ncpa packages from fedora repo (where applicable)
  yum:
    enablerepo: fedora36-nagios
    name: "{{ ncpa_packages }}"
    state: present
  when: ncpa_use_fedora_repo

- name: place ncpa config file
  template:
    src: usr.local.ncpa.etc.ncpa.cfg.j2
    dest: /usr/local/ncpa/etc/ncpa.cfg
    owner: nagios
    group: nagios
    mode: 0640
  notify: restart ncpa_listener

- name: place custom nagios plugins
  copy:
    src: "{{ item }}"
    dest: "/usr/lib64/nagios/plugins/{{ item | regex_replace('^.*usr.lib64.nagios.plugins.','') }}"
    owner: root
    group: root
    mode: 0755
  with_fileglob: usr.lib64.nagios.plugins.*

- name: place sudoers file for relevant checks
  template:
    src: etc.sudoers.d.99-nagios.j2
    dest: "/etc/sudoers.d/99-nagios"
    owner: root
    group: root
    mode: '0640'
  when: ncpa_sudoers|length > 0

- name: ensure ncpa_listener is started and enabled
  service: name=ncpa_listener state=started enabled=yes

- name: ensure ncpa_passive is disabled
  service: name=ncpa_passive state=stopped enabled=no
